#comment
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
spring:
  config:
    import:
      - optional:env.yml
  data:
    elasticsearch:
      cluster-nodes: ${elasticsearch.host}:${elasticsearch.port}
    mongodb:
      uri: mongodb://${mongodb.host}:${mongodb.port}/mydb
    redis:
      host: redis
      port: 6379
  main:
    allow-bean-definition-overriding: true


  #mysql 설정
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${mysql.master.host}:${mysql.master.port}/${mysql.master.database}?useSSL=false&serverTimezone=UTC
        read-only: false
        username: ${mysql.master.username}
        password: ${mysql.master.password}
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${mysql.slave.host}:${mysql.slave.port}/${mysql.slave.database}?useSSL=false&serverTimezone=UTC
        read-only: true
        username: ${mysql.slave.username}
        password: ${mysql.slave.password}
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
      properties:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: mysql


springdoc:
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs

