
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
    mongodb:
      uri: mongodb://localhost:27017/mydb
  main:
    allow-bean-definition-overriding: true