
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
    mongodb:
      uri: mongodb://localhost:27017/mydb
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true


  #mysql 설정
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/pickitup?characterEncoding=UTF-8&serverTimezone=UTC
        read-only: false
        username: develover
        password: ideveloveyou?
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3308/pickitup?characterEncoding=UTF-8&serverTimezone=UTC
        read-only: true
        username: develover
        password: ideveloveyou?
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
      properties:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: mysql


springdoc:
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs

