
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
    mongodb:
      uri: mongodb://localhost:27017/mydb
  main:
    allow-bean-definition-overriding: true


  #mysql 설정
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/pickitup?characterEncoding=UTF-8&serverTimezone=UTC
        read-only: false
        username: ${MYSQL_MASTER_USERNAME}
        password: ${MYSQL_MASTER_PASSWORD}
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3308/pickitup?characterEncoding=UTF-8&serverTimezone=UTC
        read-only: true
        username: ${MYSQL_SLAVE_USERNAME}
        password: ${MYSQL_SLAVE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: mysql
