version: "3.8"
services:
  mongodb:
    image: "mongo:7.0.6"
    container_name: ${MONGO_HOSTNAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - "data:/data/db"
    networks:
      - play-mongo-network
    restart: on-failure
volumes:
  data:
    driver: local
networks:
  play-mongo-network:
    external: true
